development:
  adapter: postgresql
  encoding: unicode
  database: sift_development
  pool: 5
  username: Sunmi
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sift_test
  pool: 5
  username: Sunmi
  password: 
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sift_production
  pool: 5
  username: Sunmi
  password: 
  host: localhost

